// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/session/sess.proto

package session

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success     ResultStatus = 0
	ResultStatus_MaxLimit    ResultStatus = 1
	ResultStatus_Repeated    ResultStatus = 2
	ResultStatus_NotExisted  ResultStatus = 3
	ResultStatus_DBException ResultStatus = 4
	ResultStatus_Empty       ResultStatus = 5
)

var ResultStatus_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultStatus_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{0}
}

type ReqSessionAdd struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSessionAdd) Reset()         { *m = ReqSessionAdd{} }
func (m *ReqSessionAdd) String() string { return proto.CompactTextString(m) }
func (*ReqSessionAdd) ProtoMessage()    {}
func (*ReqSessionAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{0}
}

func (m *ReqSessionAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSessionAdd.Unmarshal(m, b)
}
func (m *ReqSessionAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSessionAdd.Marshal(b, m, deterministic)
}
func (m *ReqSessionAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSessionAdd.Merge(m, src)
}
func (m *ReqSessionAdd) XXX_Size() int {
	return xxx_messageInfo_ReqSessionAdd.Size(m)
}
func (m *ReqSessionAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSessionAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSessionAdd proto.InternalMessageInfo

func (m *ReqSessionAdd) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RequestInfo struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{1}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReplyStatus struct {
	Code                 ResultStatus `protobuf:"varint,1,opt,name=code,proto3,enum=omo.msp.session.ResultStatus" json:"code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{2}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() ResultStatus {
	if m != nil {
		return m.Code
	}
	return ResultStatus_Success
}

func (m *ReplyStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Token                string       `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{3}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReplyInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqSessionRemove struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSessionRemove) Reset()         { *m = ReqSessionRemove{} }
func (m *ReqSessionRemove) String() string { return proto.CompactTextString(m) }
func (*ReqSessionRemove) ProtoMessage()    {}
func (*ReqSessionRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{4}
}

func (m *ReqSessionRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSessionRemove.Unmarshal(m, b)
}
func (m *ReqSessionRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSessionRemove.Marshal(b, m, deterministic)
}
func (m *ReqSessionRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSessionRemove.Merge(m, src)
}
func (m *ReqSessionRemove) XXX_Size() int {
	return xxx_messageInfo_ReqSessionRemove.Size(m)
}
func (m *ReqSessionRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSessionRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSessionRemove proto.InternalMessageInfo

func (m *ReqSessionRemove) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ReplyAvailable struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Available            bool         `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAvailable) Reset()         { *m = ReplyAvailable{} }
func (m *ReplyAvailable) String() string { return proto.CompactTextString(m) }
func (*ReplyAvailable) ProtoMessage()    {}
func (*ReplyAvailable) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ebe048c86d74517, []int{5}
}

func (m *ReplyAvailable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAvailable.Unmarshal(m, b)
}
func (m *ReplyAvailable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAvailable.Marshal(b, m, deterministic)
}
func (m *ReplyAvailable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAvailable.Merge(m, src)
}
func (m *ReplyAvailable) XXX_Size() int {
	return xxx_messageInfo_ReplyAvailable.Size(m)
}
func (m *ReplyAvailable) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAvailable.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAvailable proto.InternalMessageInfo

func (m *ReplyAvailable) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyAvailable) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReplyAvailable) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *ReplyAvailable) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("omo.msp.session.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterType((*ReqSessionAdd)(nil), "omo.msp.session.ReqSessionAdd")
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.session.RequestInfo")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.session.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.session.ReplyInfo")
	proto.RegisterType((*ReqSessionRemove)(nil), "omo.msp.session.ReqSessionRemove")
	proto.RegisterType((*ReplyAvailable)(nil), "omo.msp.session.ReplyAvailable")
}

func init() {
	proto.RegisterFile("proto/session/sess.proto", fileDescriptor_7ebe048c86d74517)
}

var fileDescriptor_7ebe048c86d74517 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0xc4, 0x71, 0xea, 0x71, 0x71, 0xad, 0x11, 0x07, 0x2b, 0x2a, 0x50, 0x5c, 0x09,
	0x55, 0x1c, 0x8c, 0x08, 0xbc, 0x40, 0x5b, 0x82, 0x54, 0x09, 0x90, 0x58, 0xdf, 0x7a, 0x73, 0xed,
	0x01, 0x56, 0xb5, 0xbd, 0xae, 0x77, 0x1d, 0xa5, 0x07, 0x5e, 0x80, 0x07, 0xe6, 0x8c, 0xbc, 0x76,
	0xec, 0x08, 0x59, 0x11, 0xe2, 0x94, 0x9d, 0xc9, 0x3f, 0x33, 0xdf, 0xfc, 0xbb, 0x06, 0xbf, 0xac,
	0x84, 0x12, 0x6f, 0x24, 0x49, 0xc9, 0x45, 0xa1, 0x7f, 0x43, 0x9d, 0xc2, 0x13, 0x91, 0x8b, 0x30,
	0x97, 0x65, 0xd8, 0xfd, 0x17, 0x9c, 0xc3, 0x13, 0x46, 0x0f, 0x51, 0x1b, 0x5d, 0xa6, 0x29, 0x22,
	0x98, 0xb5, 0xa4, 0xca, 0x37, 0xce, 0x8c, 0x0b, 0x9b, 0xe9, 0x73, 0x70, 0x0e, 0x0e, 0xa3, 0x87,
	0x9a, 0xa4, 0xba, 0x29, 0xbe, 0x09, 0x7c, 0x0a, 0x73, 0x25, 0xee, 0xa9, 0xe8, 0x34, 0x6d, 0x10,
	0xdc, 0x36, 0xa2, 0x32, 0x7b, 0x8c, 0x54, 0xac, 0x6a, 0x89, 0x6f, 0xc1, 0x4c, 0x44, 0x4a, 0x5a,
	0xe3, 0xae, 0x9e, 0x85, 0x7f, 0x0d, 0x0e, 0x19, 0xc9, 0x3a, 0x53, 0xad, 0x98, 0x69, 0x29, 0xfa,
	0xb0, 0xc8, 0x49, 0xca, 0xf8, 0x3b, 0xf9, 0x53, 0xdd, 0x79, 0x17, 0x06, 0x3f, 0xc1, 0xd6, 0xbd,
	0xf5, 0x78, 0x0f, 0x66, 0x35, 0x4f, 0xbb, 0xe1, 0xcd, 0xb1, 0x67, 0x9e, 0x0e, 0xcc, 0x03, 0xe4,
	0x6c, 0x0f, 0x12, 0xdf, 0x83, 0x25, 0xf5, 0x48, 0xdf, 0x3c, 0x33, 0x2e, 0x9c, 0xd5, 0xe9, 0x08,
	0x57, 0xbf, 0x03, 0xeb, 0xb4, 0xc1, 0x2b, 0xf0, 0x06, 0x93, 0x18, 0xe5, 0x62, 0x43, 0xa3, 0x3e,
	0xfd, 0x32, 0xc0, 0xd5, 0xf5, 0x97, 0x9b, 0x98, 0x67, 0xf1, 0x5d, 0x46, 0xff, 0x08, 0x7b, 0x0a,
	0x76, 0xbc, 0x2b, 0xd1, 0xc0, 0x47, 0x6c, 0x48, 0xfc, 0x1f, 0xf4, 0xeb, 0x04, 0x8e, 0xf7, 0x3d,
	0x46, 0x07, 0x16, 0x51, 0x9d, 0x24, 0x24, 0xa5, 0x37, 0xc1, 0x63, 0x38, 0xfa, 0x1c, 0x6f, 0x3f,
	0xf1, 0x9c, 0x2b, 0xcf, 0x68, 0x22, 0x46, 0x25, 0xc5, 0x8a, 0x52, 0x6f, 0x8a, 0x2e, 0xc0, 0x17,
	0xa1, 0xd6, 0x5b, 0x2e, 0x9b, 0x78, 0x86, 0x27, 0xe0, 0x7c, 0xb8, 0x5a, 0x6f, 0x13, 0x2a, 0x15,
	0x17, 0x85, 0x67, 0xa2, 0x0d, 0xf3, 0x75, 0x5e, 0xaa, 0x47, 0x6f, 0xbe, 0xfa, 0x6d, 0x80, 0xdb,
	0xf9, 0x12, 0x51, 0xb5, 0xe1, 0x09, 0xe1, 0x47, 0xb0, 0xae, 0xab, 0xa6, 0x17, 0x3e, 0x1f, 0xe1,
	0xdc, 0x7b, 0x6a, 0xcb, 0xe5, 0xf8, 0x1e, 0xcd, 0x25, 0x07, 0x13, 0xfc, 0x0a, 0xee, 0xf5, 0x0f,
	0x4a, 0xee, 0x07, 0x2f, 0xc7, 0xf6, 0xee, 0x5f, 0xe5, 0xf2, 0xc5, 0x78, 0xb7, 0xbe, 0x3c, 0x98,
	0xe0, 0x0d, 0x58, 0xdd, 0xed, 0xbd, 0x3c, 0x80, 0xd6, 0x4a, 0x0e, 0xd3, 0x5d, 0xd9, 0xb7, 0x8b,
	0x2e, 0x7d, 0x67, 0xe9, 0x4f, 0xeb, 0xdd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0xda, 0x84,
	0xbb, 0x76, 0x03, 0x00, 0x00,
}
